stages:
  - check

# Job to check the branch name and close MR if invalid
check_branch_name:
  stage: check
  script:
    - |
      # Get the current branch name
      BRANCH_NAME="${CI_COMMIT_REF_NAME}"

      # Define the required branch name pattern (e.g., feature/*, bugfix/*)
      PATTERN="^(feature|bugfix)/.*"

      # Check if the branch name matches the pattern
      if [[ ! "$BRANCH_NAME" =~ $PATTERN ]]; then
        echo "ERROR: The branch name '$BRANCH_NAME' does not match the required pattern. Closing the MR."
        
        # Make API request to close the merge request
        curl --request PUT --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
          --data "state_event=close" \
          "https://girt.ir/api/v4/projects/$CI_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID"
        
        echo "closed merge request: '$CI_MERGE_REQUEST_IID';  token: '$CI_JOB_TOKEN'; project id: '$CI_PROJECT_ID'"
        exit 1
      fi
  only:
    - merge_requests

