stages:
  - check

check_branch_name:
  stage: check
  script:
    - |
      BRANCH_NAME="${CI_COMMIT_REF_NAME}"

      PATTERN="^(feature|bugfix)/.*"

      if [[ ! "$BRANCH_NAME" =~ $PATTERN ]]; then
        echo "ERROR: The branch name '$BRANCH_NAME' does not match the required pattern. Closing the MR."
        
        curl --request PUT --header "PRIVATE-TOKEN: MMzaysyeTETq1xSHXLpi" \
          --data "state_event=close" \
          "https://girt.ir/api/v4/projects/$CI_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID"
        
        echo "closed merge request: '$CI_MERGE_REQUEST_IID';  token: '$CI_JOB_TOKEN'; project id: '$CI_PROJECT_ID'"
        exit 1
      fi
  only:
    - merge_requests

