stages:
  - check

# Job to check the branch name
check_branch_name:
  stage: check
  script:
    - |
      # Get the branch name of the source branch (the one from the MR)
      BRANCH_NAME="${CI_COMMIT_REF_NAME}"

      # Define the accepted pattern (e.g., feature/* or bugfix/*)
      PATTERN="^(feature|bugfix)/.*"

      # Check if the branch name matches the pattern
      if [[ ! "$BRANCH_NAME" =~ $PATTERN ]]; then
        echo "ERROR: The branch name '$BRANCH_NAME' does not match the required pattern."
        exit 1
      fi
  only:
    - merge_requests

